# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Libs
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error

import xgboost as xgb

from google.colab import files


train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

train_ID = train["Id"]
test_ID = test["Id"]

train.drop("Id", axis=1, inplace=True)
test.drop("Id", axis=1, inplace=True)


sns.histplot(train["SalePrice"], kde=True)


train = train[train["GrLivArea"] < 4500]
train["SalePrice"] = np.log1p(train["SalePrice"])

y = train["SalePrice"]

full_data = pd.concat([train.drop("SalePrice", axis=1), test], axis=0)
none_cols = [
    "Alley", "PoolQC", "Fence", "MiscFeature",
    "FireplaceQu", "GarageType", "GarageFinish",
    "GarageQual", "GarageCond",
    "BsmtQual", "BsmtCond", "BsmtExposure",
    "BsmtFinType1", "BsmtFinType2", "MasVnrType"
]

for col in none_cols:
    full_data[col] = full_data[col].fillna("None")

full_data["LotFrontage"] = full_data.groupby("Neighborhood")["LotFrontage"].transform(
    lambda x: x.fillna(x.median())
)

num_cols = full_data.select_dtypes(include=["int64", "float64"]).columns

for col in num_cols:
    full_data[col] = full_data[col].fillna(full_data[col].median())

cat_cols = full_data.select_dtypes(include=["object"]).columns
for col in cat_cols:
    full_data[col] = full_data[col].fillna(full_data[col].mode()[0])

full_data["TotalSF"] = (
    full_data["TotalBsmtSF"] +
    full_data["1stFlrSF"] +
    full_data["2ndFlrSF"]
)

full_data["HouseAge"] = full_data["YrSold"] - full_data["YearBuilt"]
full_data["RemodAge"] = full_data["YrSold"] - full_data["YearRemodAdd"]

full_data = pd.get_dummies(full_data)
X = full_data.iloc[:len(train), :]
X_test = full_data.iloc[len(train):, :]

kf = KFold(n_splits=5, shuffle=True, random_state=42)
rmse = []

for fold, (train_idx, val_idx) in enumerate(kf.split(X)):
    X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model = xgb.XGBRegressor(
    n_estimators=2500,
    learning_rate=0.03,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
    )

    model.fit(X_train, y_train)

    preds = model.predict(X_val)

    fold_rmse = np.sqrt(mean_squared_error(y_val, preds))
    rmse.append(fold_rmse)

    print(f"Fold {fold+1} RMSE: {fold_rmse:.5f}")

print("\nMean CV RMSE:", np.mean(rmse))

# Train final model on full data
final_model = xgb.XGBRegressor(
    n_estimators=2500,
    learning_rate=0.03,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

final_model.fit(X, y)

# Predict on test data
test_preds = final_model.predict(X_test)
test_preds = np.expm1(test_preds)
test_preds[test_preds < 0] = 0

# Create submission
submission = pd.DataFrame({
    "Id": test_ID,
    "SalePrice": test_preds
})

submission.to_csv("xgb_submission.csv", index=False)

files.download("xgb_submission.csv")

plt.figure(figsize=(10, 5))
sns.histplot(np.expm1(y), kde=True, color='skyblue', bins=50)
plt.title("Distribution of SalePrice (Original Scale)")
plt.xlabel("SalePrice")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(10, 5))
sns.histplot(test_preds, kde=True, color='orange', bins=50)
plt.title("Distribution of Predicted SalePrice")
plt.xlabel("Predicted SalePrice")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(12, 8))
xgb.plot_importance(final_model, max_num_features=20, importance_type='gain', height=0.8)
plt.title("Top 20 Feature Importances (by Gain)")
plt.show()

# Predict on training set
train_preds = final_model.predict(X)
train_preds_orig = np.expm1(train_preds)
y_orig = np.expm1(y)

plt.figure(figsize=(8, 8))
sns.scatterplot(x=y_orig, y=train_preds_orig, alpha=0.5)
plt.plot([y_orig.min(), y_orig.max()], [y_orig.min(), y_orig.max()], 'r--')
plt.xlabel("Actual SalePrice")
plt.ylabel("Predicted SalePrice")
plt.title("Predicted vs Actual SalePrice on Training Data")
plt.show()